# Generated by Django 5.0.2 on 2024-05-06 15:24

import autoslug.fields
import django.db.models.deletion
import scores.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_title', models.CharField(max_length=100)),
                ('score_slug', autoslug.fields.AutoSlugField(editable=False, populate_from='score_title', unique_with=('user',))),
                ('score_xml', models.FileField(max_length=500, upload_to=scores.models.user_directory_path)),
                ('score_json', models.FileField(max_length=500, upload_to=scores.models.user_directory_path)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
