# Generated by Django 5.0.2 on 2024-04-15 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0002_score_title_score_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
